---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(igraph)
library(here)
here::i_am("./Study 2/Cleaning/confCleaning.Rmd")
```


```{r}
rawDf <- read.csv(here("Study 2","Cleaning","input","confRaw.csv"))
posTraits <- read.csv("~/Google Drive/Volumes/Research Project/Trait Network_Behaviral/generating network/output/allPosCents.csv")

negTraits <- read.csv("~/Google Drive/Volumes/Research Project/Trait Network_Behaviral/generating network/output/allNegCents.csv")
allTraits<-rbind(posTraits,negTraits)
colnames(allTraits)[colnames(allTraits)=="trait"] <- "traits"
allTraits$Idx <- 1:296
```

```{r}
setwd("~/Google Drive/Volumes/")
posDf <- read.csv("./Research Project/Trait Network_Behaviral/generating network/output/adjacencyMatrix_p.csv")
posMat <- as.matrix(posDf)
posGraph <- graph.adjacency(posMat)

negDf <- read.csv("./Research Project/Trait Network_Behaviral/generating network/output/adjacencyMatrix_n.csv")
negMat <- as.matrix(negDf)
negGraph <- graph.adjacency(negMat)
```


```{r}
rawDf <- rawDf %>% rename(subID = id)
```

```{r}
evalProp <- rawDf %>% select(Accurate_1:Worrier_2) %>% select(ends_with("_1")) %>% apply(1, function(x) prop.table(table(x)))
confProp <- rawDf %>% select(Accurate_1:Worrier_2) %>% select(ends_with("_2")) %>% apply(1, function(x) prop.table(table(x)))
  
rawDf$evalRepeat <- as.numeric(unlist(lapply(evalProp, function(x) any(x>.95))))
rawDf$confRepeat <- as.numeric(unlist(lapply(evalProp, function(x) any(x>.95))))
```

```{r}
table((rawDf$UnderstandIns < 4 | rawDf$UnderstandIns < 4))
table(rawDf$Usable)
table(rawDf$Serious < 5)
table(rawDf$confRepeat == 1 | rawDf$evalRepeat == 1)
```



```{r}
# rawDf$remove <- ifelse(rawDf$Usable == 2 | rawDf$UnderstandTr < 4 | rawDf$UnderstandIns < 4 | rawDf$Serious < 5  | rawDf$ConDeb == 2 | rawDf$confRepeat == 1 | rawDf$evalRepeat == 1, 1, 0)
rawDf$remove <- ifelse(rawDf$evalRepeat == 1, 1, 0)
table(rawDf$remove)
rawDf <- rawDf[rawDf$remove!=1,]
```

```{r}
psych::describe(as.numeric(rawDf$D1)) # Age
prop.table(table(rawDf$D2))
prop.table(table(rawDf$D2))[4]+prop.table(table(rawDf$D2))[1]
prop.table(table(rawDf$D3))
unique(rawDf$D3)
rawDf <- rawDf %>%
  mutate(D3 = replace(D3, str_detect(rawDf$D3, ","), 8)
         )
rawDf$D3 <- case_when(
  rawDf$D3 == 1 ~ "Black",
  rawDf$D3 == 2 ~ "Asian",
  rawDf$D3 == 3 ~ "White",
  rawDf$D3 == 4 ~ "Hispanic/Latino",
  rawDf$D3 == 5 ~ "Pacific Islander",
  rawDf$D3 == 6 ~ "Native American",
  rawDf$D3 == 7 ~ "Indian",
  rawDf$D3 == 8 ~ "Mixed",
  rawDf$D3 == 9 ~ "Other",
)


prop.table(table(rawDf$D3))
sum (prop.table(table(rawDf$D3))[c(4,5,6,7)] )
```




```{r}
traitsSubset <- rawDf %>% select(subID, Accurate_1:Worrier_2)
confTraits <- traitsSubset %>% select("subID", ends_with("_2"))
confTraits<-pivot_longer(confTraits, cols=Accurate_2:Worrier_2, names_to = c("traits"), values_to = "confidence", names_repair = "unique")
confTraits$traits <- gsub("_2","",confTraits$traits)

evalTraits <- traitsSubset %>% select("subID", ends_with("_1"))
evalTraits<-pivot_longer(evalTraits, cols=Accurate_1:Worrier_1, names_to = c("traits"), values_to = "eval", names_repair = "unique")
evalTraits$traits <- gsub("_1","",evalTraits$traits)

longDf <- merge(confTraits, evalTraits, by = c("subID","traits"))

unique(longDf$traits)

longDf$traits <- gsub("\\.","-", longDf$traits)

longDf$confidence2 <- longDf$confidence^2
longDf <- longDf[!is.na(longDf$confidence),]

# Check and make sure all traits have been matched and were spelled correctly
setdiff(unique(longDf$traits), allTraits$traits)
```

```{r}
longDf <- longDf %>% left_join(allTraits, by = "traits")
```

```{r}
indDiff <- rawDf %>% select(subID,SCC1:SCC12,RSE1:CESD3,CESD4:MAIA.2_19)
```

```{r}
computeNeighbors <- function(graph, label, type = "all", var = "SE"){
  curNeigh <- neighbors(graph, label, mode = type)
  curGraph <- induced.subgraph(graph, curNeigh)
  impInd <- which(!is.na(V(curGraph)$SE))
  impGraph <- induced.subgraph(curGraph, impInd)
  if(var=="SE"){
    neighAve <- mean(V(impGraph)$SE, na.rm = TRUE)
  }else if(var=="CONF"){
    neighAve <- mean(V(impGraph)$CONF, na.rm = TRUE)
  }
    
  return(neighAve)
}

uIds <- unique(longDf$subID)
for(i in uIds){
  
  subAllSelf <- longDf[longDf$subID==i,]
  curTraits <- allTraits %>% left_join(subAllSelf, by="traits")
  
  V(posGraph)$SE <- curTraits$eval[1:148]
  V(posGraph)$CONF <- curTraits$confidence[1:148]
  V(negGraph)$SE <- curTraits$eval[149:296]
  V(negGraph)$CONF <- curTraits$confidence[149:296]
  
  for(n in 1:nrow(subAllSelf)){
    
    thisid <- subAllSelf$Idx[n]
    
    if(thisid>148){
        curLabel <- paste0("V",thisid-148)
        longDf$inSelfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(negGraph, curLabel, "in", var = "SE")
  longDf$outSelfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(negGraph, curLabel, "out", var = "SE")
  longDf$allSelfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(negGraph, curLabel, "all", var = "SE")
  
  longDf$inConfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(negGraph, curLabel, "in", var = "CONF")
  longDf$outConfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(negGraph, curLabel, "out", var = "CONF")
  longDf$outConfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(negGraph, curLabel, "all", var = "CONF")
    }else{
      curLabel <- paste0("V",thisid)
        longDf$inSelfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(posGraph, curLabel, "in", var = "SE")
  longDf$outSelfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(posGraph, curLabel, "out", var = "SE")
  longDf$allSelfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(posGraph, curLabel, "all", var = "SE")
  
  longDf$inConfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(posGraph, curLabel, "in", var = "CONF")
  longDf$outConfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(posGraph, curLabel, "out", var = "CONF")
  longDf$outConfNeigh[longDf$subID==i & longDf$Idx==thisid] <- computeNeighbors(posGraph, curLabel, "all", var = "CONF")
    }

    
  }
  
}
```


## Satisfaction with Life

```{r}
ind1 <- grep("SWLS_1", colnames(indDiff))
ind1<-min(ind1)
ind2<- grep("SWLS_5", colnames(indDiff))
ind2<-max(ind2)
# Compute score for Self-Concept Clarity Scale items
indDiff$SWLS = rowMeans(indDiff[,ind1:ind2], na.rm = TRUE)

psych::alpha(indDiff[ind1:ind2])
```

## CESD

```{r}
# Reverse code Self-Concept Clarity Scale items
CESD_revcols = c("CESD4", "CESD8", "CESD12", "CESD16")
indDiff[ ,CESD_revcols] = 5 - indDiff[ ,CESD_revcols]
ind1 <- grep("CESD", colnames(indDiff))
ind1<-min(ind1)
ind2<- grep("CESD", colnames(indDiff))
ind2<-max(ind2)
# Compute score for Self-Concept Clarity Scale items
indDiff$CESD = rowMeans(indDiff[,ind1:ind2], na.rm = TRUE)

psych::alpha(indDiff[ind1:ind2])
```

## Self-Concept Clarity

```{r}
# Reverse code Self-Concept Clarity Scale items
SCC_revcols = c("SCC1", "SCC2", "SCC3", "SCC4", "SCC5", "SCC7", 
                 "SCC8", "SCC9", "SCC10", "SCC12")
indDiff[ ,SCC_revcols] = 6 - indDiff[ ,SCC_revcols]
ind1 <- grep("SCC1", colnames(indDiff))
ind1<-min(ind1)
ind2<- grep("SCC12", colnames(indDiff))
ind2<-max(ind2)
# Compute score for Self-Concept Clarity Scale items
indDiff$SCC = rowMeans(indDiff[,ind1:ind2], na.rm = TRUE)

psych::alpha(indDiff[ind1:ind2])
```

## Self-Esteem

```{r}
# Reverse code Rosenberg Self-Esteem items
SErevcols = c("RSE2", "RSE5", "RSE6", "RSE8", "RSE9")
indDiff[ ,SErevcols] = 5 - indDiff[ ,SErevcols]
ind1 <- grep("^RSE1$", colnames(indDiff))
ind1<-min(ind1)
ind2<- grep("^RSE10$", colnames(indDiff))
ind2<-max(ind2)
# Compute scores for Rosenberg Self-Esteem
indDiff$SE = rowMeans(indDiff[, ind1:ind2], na.rm = TRUE)
indDiff$SE <- 5 - indDiff$SE
psych::alpha(indDiff[ind1:ind2])
```

## Need for Cognition

```{r}
NFCrevcols = c("NFC.6_3", "NFC.6_4")
indDiff[ ,NFCrevcols] = 8 - indDiff[ ,NFCrevcols]
ind1 <- grep("NFC.6_1", colnames(indDiff))
ind1<-min(ind1)
ind2<- grep("NFC.6_6", colnames(indDiff))
ind2<-max(ind2)
# Compute scores for Need for Cog
indDiff$NFC = rowMeans(indDiff[, ind1:ind2], na.rm = TRUE)

psych::alpha(indDiff[ind1:ind2])
```

## Dialectical Self

```{r}
columnNames <- colnames(indDiff[grep("^DS",colnames(indDiff))])
DSrevcols <- columnNames[c(1,5,6,7,9,14)]
#DSrevcols = c("DS_1", "DS_7", "DS_8", "DS_9", "DS_11","DS_17")
indDiff[ ,DSrevcols] = 8 - indDiff[ ,DSrevcols]
ind1 <- grep("DS_1", colnames(indDiff))
ind1<-min(ind1)
ind2<- grep("DS_17", colnames(indDiff))
ind2<-max(ind2)
# Compute scores for Need for Cog
indDiff$DS = rowMeans(indDiff[, ind1:ind2], na.rm = TRUE)

psych::alpha(indDiff[ind1:ind2])
```

## Interoception

```{r}
MAIArevcols = c("MAIA.1_5", "MAIA.1_6", "MAIA.1_7", "MAIA.1_8", "MAIA.1_9", "MAIA.1_10", "MAIA.1_11", "MAIA.1_12", "MAIA.1_15")
indDiff[, MAIArevcols] = 7 - indDiff[ ,MAIArevcols]
ind1 <- grep("MAIA", colnames(indDiff))
ind1 <- min(ind1)
ind2 <- grep("MAIA", colnames(indDiff))
ind2 <- max(ind2)
indDiff$MAIA <- rowMeans(indDiff[, ind1:ind2], na.rm = TRUE)
psych::alpha(indDiff[,ind1:ind2])
```



```{r}
rawDf2 <- indDiff %>% select(subID, SCC, NFC, SE, DS, CESD, SWLS, MAIA) %>% inner_join(rawDf, by = "subID", na_matches = "never")

longDf <- indDiff %>% select(subID, SCC, NFC, SE, DS, CESD, SWLS, MAIA) %>% right_join(longDf, by = "subID", na_matches = "never")
```

```{r}
longDf$devMid <- abs(4-longDf$eval)
```

```{r}
longDf <- longDf %>% group_by(subID) %>% summarise(evalBS = mean(eval, na.rm=T)) %>% full_join(longDf, by = c("subID"))
longDf <- longDf %>% group_by(subID, valence) %>% summarise(evalBSWV = mean(eval, na.rm=T)) %>% full_join(longDf, by = c("subID","valence"))
longDf <- longDf %>% group_by(traits, valence) %>% summarise(evalBT = mean(eval, na.rm=T)) %>% full_join(longDf, by = c("traits","valence"))

longDf <- longDf %>% group_by(subID) %>% summarise(confBS = mean(confidence, na.rm=T)) %>% full_join(longDf, by = c("subID"))
longDf <- longDf %>% group_by(subID, valence) %>% summarise(confBSWV = mean(confidence, na.rm=T)) %>% full_join(longDf, by = c("subID","valence"))
longDf <- longDf %>% group_by(traits, valence) %>% summarise(confBT = mean(confidence, na.rm=T)) %>% full_join(longDf, by = c("traits","valence"))

longDf$TSmean <- rowMeans(longDf[c("evalBSWV","evalBT")])

longDf$devTS <- abs(longDf$TSmean-longDf$eval)
#longDf$devT <- abs(longDf$evalBT - longDf$eval)
longDf$devT <- abs(longDf$evalBSWV - longDf$eval)
```


```{r}
longDf <- longDf %>% select(-clusterName, -cluster, -between, -eigen, -close, -efficiency, -transitivity, -pageRank)
```


```{r}
arrow::write_parquet(longDf,here("Study 2","Data","confClean2.parquet"))
```








