---
title: "R Notebook"
output: html_notebook
---


```{r}
library(groundhog)
pkgs <-  c("lmerTest", "ggeffects","r2glmm", "tidyverse","here", "sjPlot", "ggpubr", "wesanderson","NatParksPalettes")
groundhog.day <- '2022-07-25'
groundhog.library(pkgs, groundhog.day)
here::i_am("./Study 2/Analysis/finalConfAnalyses.qmd")
plotDir <- "/Volumes/Research Project/Metacognition/Study 2/Plots/"
dir.create(plotDir)
```

```{r}
longDf <- as.data.frame( arrow::read_parquet(here("Study 2/Data/confClean2.parquet")) )
```


```{r}
longDf$category.Z <- scale(longDf$category)
longDf$interpersonal.Z <- scale(longDf$interpersonal)
longDf$observability.Z <- scale(longDf$observability)
longDf$prevalence.Z <- scale(longDf$prevalence)
longDf$outConfNeigh.Z <- scale(longDf$outConfNeigh)
longDf$inConfNeigh.Z <- scale(longDf$inConfNeigh)
longDf$allSelfNeigh.Z <- scale(longDf$allSelfNeigh)
longDf$eval.Z <- scale(longDf$eval)
longDf$outDegree.Z <- scale(longDf$outDegree)
longDf$inDegree.Z <- scale(longDf$inDegree)
longDf$evalBSWV.Z <- scale(longDf$evalBSWV)
longDf$evalBSWV.Z <- scale(longDf$evalBSWV)
longDf$evalBS.Z <- scale(longDf$evalBS)
longDf$devMid.Z <- scale(longDf$devMid)
longDf$devTS.Z <- scale(longDf$devTS)
longDf$confidence.Z <- scale(longDf$confidence)
longDf$NFC.Z <- scale(longDf$NFC)
longDf$SE.Z <- scale(longDf$SE)
longDf$SCC.Z <- scale(longDf$SCC)
longDf$DS.Z <- scale(longDf$DS)
longDf$CESD.Z <- scale(longDf$CESD)
longDf$MAIA.Z <- scale(longDf$MAIA)
```


```{r}
pal <- colorRampPalette(natparks.pals("DeathValley"))(length(unique(longDf$subID)))
longDf$subID <- as.factor(longDf$subID)

plotDir <- "/Volumes/Research Project/Metacognition/Study 2/Plots/"
```

# Consistency-Confidence Plot

```{r}
m<-lmer(confidence ~ allSelfNeigh*eval + ( allSelfNeigh + eval  | subID ) + ( 1 | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
```

```{r}
p <- ggpredict(m, c("allSelfNeigh","eval[1,4,7]"))
ConsistencyConfidencePlot <-ggplot(p, aes(x, predicted)) +  geom_line(aes(linetype=group, color=group)) + geom_ribbon(aes(ymin=conf.low, ymax=conf.high, fill=group), alpha=0.15) + scale_linetype_discrete(labels = c("Low","Medium","High")) + scale_color_manual(labels = c("Low","Medium","High"), values = wes_palette("Darjeeling1")) + scale_fill_manual( 
                      labels=c("Low","Medium","High"), values = wes_palette("Darjeeling1")) + theme(
    legend.position = c(.2, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Neighboring Self-Evaluations") + ylab("Confidence")
ConsistencyConfidencePlot
ggsave(paste0(plotDir,"ConsistConf",".png"), width = 9, height = 6, dpi=500, units="in")
ggsave(paste0(plotDir,"ConsistConf",".tiff"), width = 9, height = 6, dpi=500, units="in")

ggpredict(m, c("allSelfNeigh","eval")) %>% plot(add.data=T) + labs(title="Raw Data",x="Neighboring Self-Evaluations",y="Confidence")
```

# Confidence Main Effect

```{r}
DEG.CONF<-lmer(confidence ~ inDegree + outDegree + valence + ( valence + outDegree + inDegree | subID ) + ( 1 | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
```


```{r}
mer <- ggpredict(DEG.CONF, terms = c("outDegree", "subID"), type = "re")
mef <- ggpredict(DEG.CONF, terms = c("outDegree"))

plotthat <- ggplot(mef, aes(x, predicted)) + 
  #geom_jitter(data=longDf, aes(x=outDegree,y=confidence),alpha = .007) + 
  geom_line(data=mer, aes(x=x,y=predicted, color=group), alpha= .20)  + scale_color_manual(values=pal) +  geom_line() + geom_ribbon(aes(ymin=conf.low, ymax=conf.high), alpha=0.30) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme(legend.position = "none") + xlab("Outdegree Centrality") + ylab("Confidence")  + ylim(-1,3)  + scale_y_continuous(breaks=seq(1,7,by=1))
plotthat
ggsave(paste0(plotDir,"ConfME",".png"), width = 9, height = 5, dpi=500, units="in")
ggsave(paste0(plotDir,"ConfME",".tiff"), width = 9, height = 5, dpi=500, units="in")
```

# Valence Confidence Interaction Plot

```{r}
m<-lmer( eval ~ confidence * valence + ( confidence + valence | subID ) + ( 1 | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
```


```{r}
p <- ggpredict(m, c("confidence","valence"))
ValenceDeviatePlot <-ggplot(p, aes(x, predicted)) +  geom_line(aes(linetype=group, color=group)) + geom_ribbon(aes(ymin=conf.low, ymax=conf.high, fill=group), alpha=0.15) + scale_linetype_discrete(labels = c("Negative","Positive")) + scale_color_manual(labels = c("Negative","Positive"), values = wes_palette("Darjeeling1")) + scale_fill_manual( 
                      labels=c("Negative","Positive"), values = wes_palette("Darjeeling1")) + theme(
    legend.position = c(.2, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Confidence") + ylab("SelfEvaluation") + scale_y_continuous(breaks=seq(1,7,1))
ValenceDeviatePlot
```

# Self-Concept Clarity and Confidence

```{r}
m<-lmer( confidence ~ SCC*outDegree + ( outDegree | subID ) + ( SCC | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
```


```{r}
p <- ggpredict(m, c("SCC","outDegree"))
SCC.outdeg.Conf.Plot <-ggplot(p, aes(x, predicted)) +  geom_line(aes(linetype=group, color=group)) + geom_ribbon(aes(ymin=conf.low, ymax=conf.high, fill=group), alpha=0.15) + scale_linetype_discrete(labels = c("Low Outdegree","Medium Outdegree","High Outdegree")) + scale_color_manual(labels = c("Low Outdegree","Medium Outdegree","High Outdegree"), values = wes_palette("Darjeeling1")) + scale_fill_manual( 
                      labels=c("Low Outdegree","Medium Outdegree","High Outdegree"), values = wes_palette("Darjeeling1")) + theme(
    legend.position = c(.2, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Self-Concept Clarity") + ylab("Confidence")
SCC.outdeg.Conf.Plot

ggpredict(m, c("SCC","outDegree")) %>% plot(add.data=T) + labs(title="Raw Data",x="Self-Concept Clarity",y="Confidence")
```

# Self-Esteem and Confidence

```{r}
m<-lmer( confidence ~ SE*outDegree + ( outDegree | subID ) + ( SE | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
```


```{r}
p <- ggpredict(m, c("SE","outDegree"))
SE.outdeg.Conf.Plot <-ggplot(p, aes(x, predicted)) +  geom_line(aes(linetype=group, color=group)) + geom_ribbon(aes(ymin=conf.low, ymax=conf.high, fill=group), alpha=0.15) + scale_linetype_discrete(labels = c("Low Outdegree","Medium Outdegree","High Outdegree")) + scale_color_manual(labels = c("Low Outdegree","Medium Outdegree","High Outdegree"), values = wes_palette("Darjeeling1")) + scale_fill_manual( 
                      labels=c("Low Outdegree","Medium Outdegree","High Outdegree"), values = wes_palette("Darjeeling1")) + theme(
    legend.position = c(.2, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Self-Esteem") + ylab("Confidence")
SE.outdeg.Conf.Plot

ggpredict(m, c("SE","outDegree")) %>% plot(add.data=T) + labs(title="Raw Data",x="Self-Esteem",y="Confidence")
```

# Depressive Symptoms and Confidence

```{r}
m<-lmer( confidence ~ CESD*outDegree + ( outDegree | subID ) + ( CESD | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
```


```{r}
p <- ggpredict(m, c("CESD","outDegree"))
CESD.outdeg.Conf.Plot <-ggplot(p, aes(x, predicted)) +  geom_line(aes(linetype=group, color=group)) + geom_ribbon(aes(ymin=conf.low, ymax=conf.high, fill=group), alpha=0.15) + scale_linetype_discrete(labels = c("Low Outdegree","Medium Outdegree","High Outdegree")) + scale_color_manual(labels = c("Low Outdegree","Medium Outdegree","High Outdegree"), values = wes_palette("Darjeeling1")) + scale_fill_manual( 
                      labels=c("Low Outdegree","Medium Outdegree","High Outdegree"), values = wes_palette("Darjeeling1")) + theme(
    legend.position = c(.2, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Depressive Symptoms") + ylab("Confidence")
CESD.outdeg.Conf.Plot

ggpredict(m, c("CESD","outDegree")) %>% plot(add.data=T) + labs(title="Raw Data",x="Depressive Symptoms",y="Confidence")
```

# Combined Depression, Self-Esteem, Self-Concept Clarity Plots

```{r}
ggarrange(SCC.outdeg.Conf.Plot, SE.outdeg.Conf.Plot, nrow=1, common.legend = T)
ggsave(paste0(plotDir,"IndDiff.outdegConf",".png"), width = 10.5, height = 6, units = "in")
ggsave(paste0(plotDir,"IndDiff.outdegConf",".tiff"), width = 10.5, height = 6, units = "in")
```

