---
title: "R Notebook"
output: html_notebook
---

```{r}
library(lmerTest)
library(ggeffects)
library(r2glmm)
library(tidyverse)
```

```{r}
longDf <- read.csv("/Volumes/GoogleDrive/My Drive/Volumes/Research Project/Metacognition/Study 1/input/confClean.csv")
```



```{r}
m<-lmer(scale(devMid) ~ scale(inConfNeigh) + scale(confidence) * scale(outConfNeigh) + (  1 | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("confidence","outConfNeigh")) %>% plot()
```

```{r}
m<-lmer(scale(outConfNeigh) ~ scale(confidence) + (  scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("confidence","valence")) %>% plot()
```

```{r}
m<-lmer(scale(inConfNeigh) ~ scale(confidence) + (  scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("confidence")) %>% plot()
```

```{r}
longDf$outsPE <- longDf$eval-longDf$outSelfNeigh
longDf$insPE <- longDf$eval-longDf$inSelfNeigh
m<-lmer(scale(confidence) ~ scale(outsPE)*valence + scale(insPE)*valence + (  scale(outsPE)+valence+scale(insPE)  | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("outsPE","valence")) %>% plot()
```

```{r}
longDf$aPE <- abs(longDf$eval-longDf$allSelfNeigh)
m<-lmer(scale(confidence) ~ scale(aPE)*valence + (  scale(aPE)+valence  | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("aPE","valence")) %>% plot()

m<-lmer(scale(confidence) ~ scale(aPE)*scale(outDegree) + (  scale(aPE)+scale(outDegree)  | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("outDege","aPE")) %>% plot()

m<-lmer(scale(eval) ~ scale(allSelfNeigh)*scale(confidence) + (  scale(allSelfNeigh)+scale(confidence)  | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("allSelfNeigh","confidence")) %>% plot()

m<-lmer(scale(confidence) ~ scale(allSelfNeigh)*scale(eval) + (  scale(allSelfNeigh)+scale(eval)  | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("allSelfNeigh","eval")) %>% plot()
```



# Centrality Predicts Confidence

```{r}
m<-lmer(scale(confidence) ~ scale(outDegree) + scale(inDegree) + valence + scale(outDegree) + scale(inDegree) + scale(eval) + (  valence + scale(outDegree) | subID ) + ( 1 | traits), data=longDf)
summary(m)
```


```{r}
m<-lmer(scale(confidence) ~ scale(outDegree)+ ( scale(outDegree) | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(outDegree)*valence + ( scale(outDegree)+valence | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(inDegree) + ( scale(inDegree) | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(inDegree) + scale(outDegree) + valence + ( valence + scale(outDegree) | subID ) + ( 1 | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2beta(m)
```

# Extreme Responses

```{r}
m<-lmer(scale(devMid) ~ scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)
r2glmm::r2beta(m)

m<-lmer(scale(devTS) ~ scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2glmm::r2beta(m)

m<-lmer(scale(eval) ~ scale(confidence) + scale(evalBSWV) + scale(evalBT) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)
r2glmm::r2beta(m)

m<-lmer(scale(eval) ~ scale(confidence)*valence + ( scale(confidence) + valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
r2glmm::r2beta(m)
ggpredict(m, c("confidence","valence")) %>% plot()
```

```{r}
detach("package:lmerTest", unload=TRUE)
longDf$confidence.Z <- scale(longDf$confidence)
longDf$devMid.Z <- scale(longDf$devMid)
longDf$outDegree.Z <- scale(longDf$outDegree)
model.0 <- lmer(devMid.Z ~ outDegree.Z + ( 1 | subID ) , data=longDf[!is.na(longDf$confidence),])
model.M <- lmer( confidence.Z ~ outDegree.Z + ( 1 | subID ) , data=longDf[!is.na(longDf$devMid),])
model.Y <- lmer( devMid.Z ~ confidence.Z + outDegree.Z + ( confidence.Z | subID ) , data=longDf)
library(mediation)
results <- mediate(model.M, model.Y, treat='outDegree.Z', mediator='confidence.Z',
                   boot=F, sims=500)
summary(results)
```

```{r}
longDf$confidence.Z <- scale(longDf$confidence)
longDf$devMid.Z <- scale(longDf$devMid)
longDf$outDegree.Z <- scale(longDf$outDegree)
model.0 <- lmer(devMid.Z ~ outDegree.Z + ( 1 | subID ) , data=longDf[!is.na(longDf$confidence),])
model.M <- lmer( outDegree.Z ~ confidence.Z + ( confidence.Z | subID ) , data=longDf[!is.na(longDf$devMid),])
model.Y <- lmer( devMid.Z ~ confidence.Z + outDegree.Z + ( confidence.Z | subID ) , data=longDf)
library(mediation)
results <- mediate(model.M, model.Y, treat='confidence.Z', mediator='outDegree.Z',
                   boot=F, sims=500)
summary(results)
library(lmerTest)
```


# Manipulation

## Main Effect

```{r}
m<-lmer(scale(confidence) ~ COND + ( 1 | subID ) + ( COND | traits), data=longDf)
summary(m)
ggpredict(m, c("COND")) %>% plot()
```

## Interactions

```{r}
m<-lmer(scale(confidence) ~ COND + valence + ( valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
library(Mum)
ggpredict(m, c("eval","COND")) %>% plot()

m<-lmer(scale(confidence) ~ COND * scale(devMid) + ( scale(devMid) | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("devMid","COND")) %>% plot()

m<-lmer(scale(confidence) ~ COND * scale(outDegree) + ( 1 | subID ) + ( COND | traits), data=longDf)
summary(m)
ggpredict(m, c("outDegree","COND")) %>% plot()

m<-lmer(scale(confidence) ~ COND * scale(inDegree) + ( 1 | subID ) + ( COND | traits), data=longDf)
summary(m)
ggpredict(m, c("outDegree","COND")) %>% plot()

m<-lmer(scale(confidence) ~ COND * scale(inDegree)+ scale(outDegree) + valence + scale(devMid) + ( valence + scale(devMid)  | subID ) + ( COND | traits), data=longDf)
summary(m)
ggpredict(m, c("outDegree","COND")) %>% plot()
```

# Individual Differences Predicting Confidence

```{r}
m<-lmer(scale(confidence) ~ scale(SCC) + ( 1 | subID ) + ( scale(SCC) | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(NFC) + ( 1 | subID ) + ( scale(NFC) | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(SE) + ( 1 | subID ) + ( scale(SE) | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(DS) + ( 1 | subID ) + ( scale(DS) | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(MAIA) + ( 1 | subID ) + ( scale(MAIA) | traits), data=longDf)
summary(m)

m<-lmer(scale(confidence) ~ scale(CESD) + ( 1 | subID ) + ( scale(CESD) | traits), data=longDf)
summary(m)
```

# Individual Differences Interacting with Valence in Predicting Confidence

```{r}
m<-lmer(scale(confidence) ~ scale(SCC) * valence + ( valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("SCC","valence")) %>% plot()

m<-lmer(scale(confidence) ~ scale(NFC) * valence + ( valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("NFC","valence")) %>% plot()

m<-lmer(scale(confidence) ~ scale(SE) * valence + ( valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("SE","valence")) %>% plot()

m<-lmer(scale(confidence) ~ scale(DS) * valence + ( valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("DS","valence")) %>% plot()

m<-lmer(scale(confidence) ~ scale(MAIA) * valence + ( valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("MAIA","valence")) %>% plot()

m<-lmer(scale(confidence) ~ scale(CESD) * valence + ( valence | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("CESD","valence")) %>% plot()
```

# Individual Differences Interacting with Outdegree in Predicting Confidence

```{r}
m<-lmer(scale(confidence) ~ scale(SCC) * scale(outDegree) + ( scale(outDegree) | subID ) + ( scale(SCC) | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2beta(m)
ggpredict(m, c("SCC","outDegree")) %>% plot()

m<-lmer(scale(confidence) ~ scale(NFC) * scale(outDegree) + ( scale(outDegree) | subID ) + ( scale(NFC) | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2beta(m)
ggpredict(m, c("NFC","outDegree")) %>% plot()

m<-lmer(scale(confidence) ~ scale(SE) * scale(outDegree) + ( scale(outDegree)  | subID ) + ( scale(SE) | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2beta(m)
ggpredict(m, c("SE","outDegree")) %>% plot()

m<-lmer(scale(confidence) ~ scale(DS) * scale(outDegree) + ( scale(outDegree)  | subID ) + ( scale(DS) | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2beta(m)
ggpredict(m, c("DS","outDegree")) %>% plot()

m<-lmer(scale(confidence) ~ scale(MAIA) * scale(outDegree) + ( scale(outDegree)  | subID ) + ( scale(MAIA) | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2beta(m)
ggpredict(m, c("MAIA","outDegree")) %>% plot()

m<-lmer(scale(confidence) ~ scale(CESD) * scale(outDegree) + ( scale(outDegree)  | subID ) + ( scale(CESD) | traits), data=longDf, control=lmerControl(optimizer="bobyqa",
                                 optCtrl=list(maxfun=2e5)))
summary(m)
r2beta(m)
ggpredict(m, c("CESD","outDegree")) %>% plot()
```

```{r}
m<-lmer(scale(devMid) ~ scale(SCC) * scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(devMid) ~ scale(NFC) * scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(devMid) ~ scale(SE) * scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(devMid) ~ scale(DS) * scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(devMid) ~ scale(MAIA) * scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)

m<-lmer(scale(devMid) ~ scale(CESD) * scale(confidence) + ( scale(confidence) | subID ) + ( 1 | traits), data=longDf)
summary(m)
```




```{r}
m<-lmer(scale(confidence) ~ COND * MAIA  + ( 1   | subID ) + ( COND | traits), data=longDf)
summary(m)
ggpredict(m, c("MAIA","COND")) %>% plot()
```

```{r}
m<-lmer(scale(confidence) ~ COND * valence  * scale(eval) + ( valence  + scale(eval)  | subID ) + ( COND | traits), data=longDf)
summary(m)
ggpredict(m, c("eval","valence","COND")) %>% plot()
```

```{r}
m<-lmer(scale(confidence) ~ COND*scale(eval) + scale(desirability) + scale(prevalence) + scale(observability) + ( scale(eval)  | subID ) + ( 1 | traits), data=longDf)
summary(m)
ggpredict(m, c("eval","COND")) %>% plot()
```


```{r}
m <- lm(scale(SCC) ~ COND, data = longDf)
summary(m)
ggpredict(m, c("COND")) %>% plot()
```


```{r}
m <- lm(scale(Race_Id) ~ COND, data = longDf)
summary(m)
ggpredict(m, c("COND")) %>% plot()

m <- lm(scale(Gender_Id) ~ COND, data = longDf)
summary(m)
ggpredict(m, c("COND")) %>% plot()

m <- lm(Sexual_Id ~ COND, data = longDf)
summary(m)
ggpredict(m, c("COND")) %>% plot()

m <- lm(Political_Id ~ COND, data = longDf)
summary(m)
ggpredict(m, c("COND")) %>% plot()

m <- lm(Student_Id ~ COND, data = longDf)
summary(m)
ggpredict(m, c("COND")) %>% plot()

table(longDf$COND)
```

